Add matrix reading helper script and fix some script issues

diff --git a/scripts/run_mumps.sh.in b/scripts/run_mumps.sh.in
--- a/scripts/run_mumps.sh.in
+++ b/scripts/run_mumps.sh.in
@@ -7,6 +7,11 @@ if [[ $# != 10 ]]; then
     exit 1
 fi
 
+if [[ $1 == "-h" || $1 == "--help" ]]; then
+    printf "\e[33mUSAGE:\e[0m %s job n bandwidth density symmetry num_proc num_threads par inctl13 ordering\n" "$0"
+    exit 0
+fi
+
 job=$1
 n=$2
 bandwidth=$3
@@ -23,10 +28,10 @@ ordering=${10}
 #
 # type=$1
 # case $type in
-#     real)
+#     "real")
 #         type_int=0
 #         ;;
-#     complex)
+#     "complex")
 #         type_int=1
 #         ;;
 #     *)
@@ -34,7 +39,6 @@ ordering=${10}
 #         exit 1
 #         ;;
 # esac
-# type="real"
 type_int=0
 
 do_analysis=0
@@ -60,10 +64,6 @@ case "$job" in
 "afe")
     do_analysis=1
     do_factorization=1
-    ;;
-"-h")
-    printf "\e[33mUSAGE:\e[0m %s job n bandwidth density symmetry num_proc num_threads par inctl13 ordering\n" "$0"
-    exit 0
     ;;
 *)
     printf >&2 "\e[31mERROR\e[0m Wrong job value: %s (possible: at, ae, ft, fe, aft, afe)\n" "$job"
@@ -112,6 +112,9 @@ if [[ $(echo "$icntl_13" | grep -E -o "([1-9][0-9]*)|-1|0") == "" ]]; then
 fi
 
 case "$ordering" in
+"automatic")
+    ordering_int=0
+    ;;
 "metis")
     ordering_int=1
     ;;
@@ -125,7 +128,7 @@ case "$ordering" in
     ordering_int=4
     ;;
 *)
-    printf >&2 "\e[31mERROR\e[0m %s is not a proper ordering parameter (metis, pord, scotch, ptscotch)\n" "$ordering"
+    printf >&2 "\e[31mERROR\e[0m %s is not a proper ordering parameter (automatic, metis, pord, scotch, ptscotch)\n" "$ordering"
     exit 11
     ;;
 esac
@@ -212,7 +215,7 @@ esac
 
 printf "%s\n" "$result" >>launch.log
 if [[ -z "$result" ]]; then
-    printf >&2 "\e[31mERROR\e[0m An error occured during the execution\n"
+    printf >&2 "\e[31mERROR\e[0m An error occured during the measure\n"
     exit 15
 fi
 
